<Project Sdk="Godot.NET.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>11.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting" Version="4.14.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Resources\**" />
    <Compile Remove="NewRecipeIdea\**" />
    <Compile Remove="Scripts\Managers\Data\**" />
    <Compile Remove="Scripts\Managers\WorldManager\**" />
    <Compile Remove="Scripts\GameObjects\WorldObjectProperty\**" />
    <Compile Remove="Scripts\GameObjects\WorldObject\**" />
    <Compile Remove="Scripts\Resources\WorldObject\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Scripts\**" />
    <EmbeddedResource Remove="Resources\**" />
    <EmbeddedResource Remove="NewRecipeIdea\**" />
    <EmbeddedResource Remove="Scripts\Managers\Data\**" />
    <EmbeddedResource Remove="Scripts\Managers\WorldManager\**" />
    <EmbeddedResource Remove="Scripts\GameObjects\WorldObjectProperty\**" />
    <EmbeddedResource Remove="Scripts\GameObjects\WorldObject\**" />
    <EmbeddedResource Remove="Scripts\Resources\WorldObject\**" />
  </ItemGroup>
  <ItemGroup>
    <!--Required for GdUnit4-->
    <PackageReference Include="gdUnit4.api" Version="4.2.0-rc*" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scripts\GameObjects\NewDirectory1\" />
  </ItemGroup>
</Project>