<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>11.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="GameManagers\**" />
    <Compile Remove="OLD\tests\**" />
    <Compile Remove="Scripts\**" />
    <Compile Remove="Builders\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="GameManagers\**" />
    <EmbeddedResource Remove="OLD\tests\**" />
    <EmbeddedResource Remove="Scripts\**" />
    <EmbeddedResource Remove="Builders\**" />
  </ItemGroup>
  <ItemGroup>
    <!--Required for GdUnit4-->
    <PackageReference Include="gdUnit4.api" Version="4.2.0-rc*" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="tests\BlockHealthTest.txt" />
    <Content Include="tests\BlockStabilityTest.txt" />
    <Content Include="tests\BlockTest.txt" />
    <Content Include="tests\BlockTestHelpers.txt" />
  </ItemGroup>
</Project>