<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="OLD\todo.txt" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="GameManagers\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="GameManagers\**" />
  </ItemGroup>
</Project>